### ISSUE TITLE
fail with gevent

### ISSUE THREAD

**Issue by dantezhu** [coleifer/flask-peewee#42]
when i use flask_peewee with gevent, it will fail, but when i change flask_peewee to pure peewee, it will be ok.

the error is bellow:

<pre>
Traceback (most recent call last):
  File "build/bdist.macosx-10.7-intel/egg/gevent/wsgi.py", line 114, in handle
    result = self.server.application(env, self.start_response)
  File "/Library/Python/2.7/site-packages/Flask-0.9-py2.7.egg/flask/app.py", line 1701, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Library/Python/2.7/site-packages/Flask-0.9-py2.7.egg/flask/app.py", line 1689, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Library/Python/2.7/site-packages/Flask-0.9-py2.7.egg/flask/app.py", line 1687, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/2.7/site-packages/Flask-0.9-py2.7.egg/flask/app.py", line 1362, in full_dispatch_request
    response = self.process_response(response)
  File "/Library/Python/2.7/site-packages/Flask-0.9-py2.7.egg/flask/app.py", line 1564, in process_response
    response = handler(response)
  File "/Library/Python/2.7/site-packages/flask_peewee-0.5.4-py2.7.egg/flask_peewee/db.py", line 48, in close_db
    self.database.close()
  File "build/bdist.macosx-10.7-intel/egg/peewee.py", line 301, in close
    self.adapter.close(self.__local.conn)
  File "build/bdist.macosx-10.7-intel/egg/peewee.py", line 117, in close
    conn.close()
ProgrammingError: closing a closed connection
<WSGIServer fileno=5 address=0.0.0.0:5000>: Failed to handle request:
  request = <http_request "GET /get HTTP/1.1" 127.0.0.1:50798>
  application = <flask.app.Flask object at 0x10b900610>
</pre>

**Comment by lyssdod** [comment]
@coleifer can it be added to main peewee docs as well? because now they lack it and I just hit the problem using plain peewee + gevent (only monkey patching everything
 without this setting)

**Comment by coleifer** [comment]
@lyssdod what exactly do you want to see added?

Docs: http://docs.peewee-orm.com/en/latest/peewee/database.html#async-with-gevent

**Comment by lyssdod** [comment]
`threadlocals=True` . I'm using pymysql and getting lots of these errors:
```
2019-07-01 11:38:18 1551275072 [Warning] Aborted connection 182 to db: 'db5' user: 'user5' host: 'localhost' (Got an error reading communication packets)
2019-07-01 11:38:18 1551275072 [Warning] Aborted connection 182 to db: 'db5' user: 'user5' host: 'localhost' (CLOSE_CONNECTION)
2019-07-01 11:38:18 1550865472 [Warning] Aborted connection 183 to db: 'db5' user: 'user5' host: 'localhost' (Got an error reading communication packets)
2019-07-01 11:38:18 1550865472 [Warning] Aborted connection 183 to db: 'db5' user: 'user5' host: 'localhost' (CLOSE_CONNECTION)
2019-07-01 11:38:19 1464431680 [Warning] Aborted connection 184 to db: 'db5' user: 'user5' host: 'localhost' (Got an error reading communication packets)
2019-07-01 11:38:19 1464431680 [Warning] Aborted connection 184 to db: 'db5' user: 'user5' host: 'localhost' (CLOSE_CONNECTION)
2019-07-01 11:38:21 1464226880 [Warning] Aborted connection 185 to db: 'db5' user: 'user5' host: 'localhost' (Got an error reading communication packets)
2019-07-01 11:38:21 1464226880 [Warning] Aborted connection 185 to db: 'db5' user: 'user5' host: 'localhost' (CLOSE_CONNECTION)
```

(connection number is growing). If I disable monkey patching of thread, error is gone

**Comment by lyssdod** [comment]
hm, it looks like it's already `True` since `2.3.3` (I'm using 3.9.6) :/

**Comment by coleifer** [comment]
Might have something to do with where you're applying the monkey-patch. It needs to be before *any* code or modules are imported.

**Comment by lyssdod** [comment]
that's exactly my case. the only thing I can think of now is outdated pymysql version (I'm using `0.7.3`)

**Comment by coleifer** [comment]
I'm not sure what to tell you. You're hopefully patching everything -- thread, socket, etc., via `patch_all()`.

**Comment by lyssdod** [comment]
yes :( I will try to update pymysql to the latest version and then create new issue at the main repo if problem persists.
